[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_MAPBOX_TOKEN = "pk.eyJ1IjoibWlsa3NsYXBwZXIiLCJhIjoiY21hYzEyNHo0MTZydDJscTFkNDNtcTZmcCJ9.OdSvJgYrMd3VydiC9zXHEw"
  NEXT_PUBLIC_API_URL = "http://localhost:3000"
  NEXT_PUBLIC_SUPABASE_URL = "https://mbtgrvmnownfbwhlgvbw.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBh..."
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_51RWHZjCcOg8nBLRtILbVeeuKzYoPa..."
  STRIPE_SECRET_KEY = "sk_test_51RWHZjCcOg8nBLRtibAjW1WK3YaMi..."
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  STRIPE_WEBHOOK_SECRET = "whsec_270aef6f3af0f19ba5d9c0784c8072d4e45621a03f15bb623ba67ceeda5b6ffe"


[functions]
  node_bundler = "esbuild"
